# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_id', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('player_tag', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cards_earned', models.CharField(max_length=200)),
                ('battles_played', models.CharField(max_length=200)),
                ('wins', models.CharField(max_length=200)),
            ],
        ),
    ]
