# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClanStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_img', models.URLField(default='https://royaleapi.com/static/img/badge/no_clan.png')),
                ('battles_played', models.IntegerField()),
                ('crowns', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('participants', models.IntegerField()),
                ('clan_tag', models.CharField(max_length=100)),
                ('war_trophies', models.IntegerField()),
                ('war_trophies_change', models.IntegerField()),
                ('war_trophies_start', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('war_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tag', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('trophies', models.IntegerField()),
                ('arena_number', models.CharField(max_length=200)),
                ('arena_name', models.CharField(max_length=200)),
                ('clan_name', models.CharField(max_length=200)),
                ('clan_tag', models.CharField(max_length=200)),
                ('clan_img', models.URLField(default='https://royaleapi.com/static/img/badge/no_clan.png')),
                ('role', models.CharField(max_length=200)),
                ('donations', models.IntegerField(default=0)),
                ('donations_delta', models.IntegerField(default=0)),
                ('donatios_received', models.IntegerField(default=0)),
                ('cards_found', models.IntegerField(default=0)),
                ('challenge_cards', models.IntegerField(default=0)),
                ('challenge_max_wins', models.IntegerField(default=0)),
                ('clan_cards_collected', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('max_trophies', models.IntegerField(default=0)),
                ('current_best_trophies', models.IntegerField(default=0)),
                ('best_season_trophies', models.IntegerField(default=0)),
                ('previous_season_trophies', models.IntegerField(default=0)),
                ('three_crown_wins', models.IntegerField(default=0)),
                ('total_donations', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('draws_percent', models.FloatField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('losses_percent', models.FloatField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('war_day_wins', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('wins_percent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WarParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_id', models.CharField(max_length=200)),
                ('time_id', models.DateTimeField(default=datetime.datetime.now)),
                ('season', models.CharField(max_length=200)),
                ('player_tag', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cards_earned', models.CharField(max_length=200)),
                ('battles_played', models.CharField(max_length=200)),
                ('wins', models.CharField(max_length=200)),
                ('clan_tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='warparticipation',
            unique_together=set([('war_id', 'season', 'player_tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('player_tag',)]),
        ),
        migrations.AlterUniqueTogether(
            name='clanstandings',
            unique_together=set([('war_id', 'clan_tag')]),
        ),
    ]
