# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_tag', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('trophies', models.IntegerField()),
                ('arena_number', models.CharField(max_length=200)),
                ('arena_name', models.CharField(max_length=200)),
                ('clan_name', models.CharField(max_length=200)),
                ('clan_tag', models.CharField(max_length=200)),
                ('clan_img', models.URLField()),
                ('role', models.CharField(max_length=200)),
                ('donations', models.IntegerField()),
                ('donations_delta', models.IntegerField()),
                ('donatios_received', models.IntegerField()),
                ('cards_found', models.IntegerField()),
                ('challenge_cards', models.IntegerField()),
                ('challenge_max_wins', models.IntegerField()),
                ('clan_cards_collected', models.IntegerField()),
                ('level', models.IntegerField()),
                ('max_trophies', models.IntegerField()),
                ('three_crown_wins', models.IntegerField()),
                ('total_donations', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('draws_percent', models.FloatField()),
                ('losses', models.IntegerField()),
                ('losses_percent', models.FloatField()),
                ('total_games', models.IntegerField()),
                ('war_day_wins', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('wins_percent', models.FloatField()),
            ],
        ),
    ]
