# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warparticipation',
            name='time_id',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='warparticipation',
            name='war_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='warparticipation',
            unique_together=set([('war_id', 'season', 'player_tag')]),
        ),
    ]
