# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warparticipation',
            unique_together=set([('war_id', 'player_tag')]),
        ),
    ]
