# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0003_auto_20180528_2300'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('player_tag',)]),
        ),
    ]
