# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0004_auto_20180528_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='best_season_trophies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='curret_best_trophies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='previous_season_trophies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
