# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0005_auto_20180529_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='curret_best_trophies',
            new_name='current_best_trophies',
        ),
    ]
