# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanwar', '0006_auto_20180529_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='best_season_trophies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_best_trophies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='previous_season_trophies',
            field=models.IntegerField(default=0),
        ),
    ]
